use role accountadmin;

use warehouse compute_wh;

use schema MYDB.MYSCHEMA;


//===== Time Travel (Deleting some rows)=========

CREATE OR REPLACE TABLE DROP_TABLE
(
    ID INT,
    NAME VARCHAR
);

INSERT INTO DROP_TABLE VALUES
    (1, 'JOHN'),
    (2, 'SAM'),
    (3, 'ELAN'),
    (4, 'MARK');

DELETE FROM DROP_TABLE WHERE ID = 4;

select * from drop_table;

SELECT * FROM DROP_TABLE AT(OFFSET => -60*3);

show tables;

SELECT * FROM DROP_TABLE AT(TIMESTAMP => '2026-04-07 14:43:30.020 -0700'::timestamp_tz);

SELECT * FROM DROP_TABLE BEFORE(STATEMENT => '01c38ed7-0004-f926-000c-8a5200026656');


--Now lets restore the old table 
CREATE OR REPLACE TABLE DROP_TABLE_CLONE AS
SELECT * FROM DROP_TABLE BEFORE(STATEMENT => '01c38ed7-0004-f926-000c-8a5200026656');

TRUNCATE TABLE DROP_TABLE;

INSERT INTO DROP_TABLE
SELECT * FROM DROP_TABLE_CLONE;

DROP TABLE DROP_TABLE_CLONE;

SELECT * FROM DROP_TABLE;


//=====Dropping table, schema and database =====
--Another method of restroing mistakes(or deleted or dropped data)

DROP TABLE DROP_TABLE;

SELECT * FROM DROP_TABLE;

UNDROP TABLE DROP_TABLE;

DROP SCHEMA MYSCHEMA;

UNDROP SCHEMA MYSCHEMA;

DROP DATABASE MYDB;

UNDROP DATABASE MYDB;

USE SCHEMA MYDB.MYSCHEMA;

SHOW DATABASES;

SHOW SCHEMAS;

SHOW TABLES;

USE SCHEMA MYDB.MYSCHEMA;

ALTER TABLE DROP_TABLE SET DATA_RETENTION_TIME_IN_DAYS = 30;